'use client'

import { Clock3, Download } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { auditLogs, versions } from '@/lib/utilities-data'

function SectionTitle({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) { return <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[0.18em] text-primary">{eyebrow}</p><h1 className="text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p>}</div>{action}</div> }

export function AuditView({ onNotify }: { onNotify: (m: string) => void }) { return <div className="flex flex-col gap-7"><SectionTitle eyebrow="Trazabilidad" title="Auditoría" description="Consulta la bitácora de cambios y versiones del cálculo." action={<Button variant="outline" onClick={() => onNotify('Exportando bitácora')}><Download className="mr-2 size-4" />Exportar bitácora</Button>} /><div className="grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><Card><CardHeader><CardTitle>Actividad reciente</CardTitle><CardDescription>Todas las acciones quedan registradas.</CardDescription></CardHeader><CardContent><div className="flex flex-col gap-5">{auditLogs.map((log) => <div key={log.id} className="flex gap-3"><div className="mt-1 flex size-7 shrink-0 items-center justify-center rounded-full bg-primary/8 text-primary"><Clock3 className="size-3.5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-medium">{log.action}</p><span className="text-xs text-muted-foreground">{log.date}</span></div><p className="mt-1 text-xs text-muted-foreground">{log.detail}</p><p className="mt-1 text-xs text-primary">{log.user}</p></div></div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Versiones</CardTitle><CardDescription>Historial de reprocesos.</CardDescription></CardHeader><CardContent><div className="flex flex-col gap-3">{versions.map((v, i) => <div key={v.id} className={`rounded-lg border p-3 ${i === 0 ? 'border-primary/30 bg-primary/5' : 'border-border/70'}`}><div className="flex justify-between"><p className="font-semibold">v{v.version}</p>{i === 0 && <Badge variant="secondary">Actual</Badge>}</div><p className="mt-1 text-xs text-muted-foreground">{v.reason}</p><p className="mt-2 text-[11px] text-muted-foreground">{v.date} · {v.user}</p></div>)}</div></CardContent></Card></div></div> }
