'use client'

import { ShieldCheck } from 'lucide-react'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { company } from '@/lib/utilities-data'

function SectionTitle({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) { return <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[0.18em] text-primary">{eyebrow}</p><h1 className="text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p>}</div>{action}</div> }

export function ConfigurationView({ onNotify }: { onNotify: (m: string) => void }) { return <div className="flex flex-col gap-7"><SectionTitle eyebrow="Parámetros legales" title="Configuración del ejercicio" description="Define la base legal y las reglas que utilizará el motor de cálculo." action={<Button onClick={() => onNotify('Configuración guardada')}>Guardar cambios</Button>} /><div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>Datos de la empresa</CardTitle><CardDescription>Información tributaria del ejercicio.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><div><p className="text-xs text-muted-foreground">Razón social</p><p className="mt-1 font-medium">{company.name}</p></div><div><p className="text-xs text-muted-foreground">Actividad económica</p><p className="mt-1 font-medium">{company.activity}</p></div><div><p className="text-xs text-muted-foreground">Renta neta anual</p><Input defaultValue="1,500,000.00" className="mt-1" /></div></CardContent></Card><Card><CardHeader><CardTitle>Reglas de distribución</CardTitle><CardDescription>Valores derivados de la actividad.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><div className="grid grid-cols-2 gap-3"><div className="rounded-lg border border-border/70 p-3"><p className="text-xs text-muted-foreground">Porcentaje legal</p><p className="mt-1 text-2xl font-semibold text-primary">10%</p></div><div className="rounded-lg border border-border/70 p-3"><p className="text-xs text-muted-foreground">Tope individual</p><p className="mt-1 text-2xl font-semibold">18×</p></div></div><Alert><ShieldCheck className="size-4" /><AlertTitle>Configuración validada</AlertTitle><AlertDescription>La actividad de servicios financieros aplica un 10% sobre la renta neta.</AlertDescription></Alert></CardContent></Card></div></div> }
