'use client'

import { AlertCircle, ArrowDownToLine, Calculator, Check, ShieldCheck } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Separator } from '@/components/ui/separator'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { getTotals, money } from '@/lib/utilities-calculation'
import type { EmployeeUtilityResult } from './types'

function SectionTitle({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) { return <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[0.18em] text-primary">{eyebrow}</p><h1 className="text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p>}</div>{action}</div> }
function Kpi({ label, value, hint, tone = 'default', icon: Icon }: { label: string; value: string; hint: string; tone?: 'default' | 'teal' | 'amber' | 'rose'; icon: typeof Calculator }) { return <Card className="border-border/70 shadow-sm"><CardContent className="flex items-start justify-between p-5"><div><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-2 text-xl font-semibold tracking-tight">{value}</p><p className={`mt-1 text-xs ${tone === 'rose' ? 'text-rose-400' : tone === 'amber' ? 'text-amber-400' : tone === 'teal' ? 'text-teal-400' : 'text-muted-foreground'}`}>{hint}</p></div><div className={`rounded-lg p-2.5 ${tone === 'teal' ? 'bg-teal-500/10 text-teal-400' : tone === 'amber' ? 'bg-amber-500/10 text-amber-400' : tone === 'rose' ? 'bg-rose-500/10 text-rose-400' : 'bg-primary/8 text-primary'}`}><Icon className="size-4" /></div></CardContent></Card> }

export function RemaindersView({ results, totals }: { results: EmployeeUtilityResult[]; totals: ReturnType<typeof getTotals> }) { const capped = results.filter((r) => r.remainder > 0); return <div className="flex flex-col gap-7"><SectionTitle eyebrow="Conciliación" title="Remanentes" description="Excedentes generados por la aplicación del tope individual de 18 remuneraciones." /><div className="grid gap-4 sm:grid-cols-3"><Kpi label="Fondo legal" value={money.format(totals.fund)} hint="Base del ejercicio" icon={ShieldCheck} tone="teal" /><Kpi label="Distribuido" value={money.format(totals.distributed)} hint="Monto final asignado" icon={ArrowDownToLine} /><Kpi label="Remanente" value={money.format(totals.remainder)} hint="Pendiente de destino" icon={AlertCircle} tone="amber" /></div><Card><CardHeader><div className="flex items-center justify-between"><div><CardTitle>Conciliación del fondo</CardTitle><CardDescription>Fondo = Distribuido + Remanente</CardDescription></div><Badge variant="outline" className="bg-emerald-500/10 text-emerald-400"><Check className="mr-1 size-3" />Conciliado</Badge></div></CardHeader><CardContent><div className="flex flex-col gap-4"><div className="flex items-center justify-between rounded-lg bg-muted/50 p-4 text-sm"><span>Fondo total</span><span className="font-semibold">{money.format(totals.fund)}</span></div><div className="flex items-center justify-between px-4 text-sm text-muted-foreground"><span>− Distribuido a trabajadores</span><span>{money.format(totals.distributed)}</span></div><Separator /><div className="flex items-center justify-between rounded-lg bg-amber-500/10 p-4 text-sm text-amber-400"><span className="font-medium">Remanente identificado</span><span className="font-semibold">{money.format(totals.remainder)}</span></div></div></CardContent></Card><Card><CardHeader><CardTitle>Detalle de excedentes</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Trabajador</TableHead><TableHead>Preliminar</TableHead><TableHead>Tope aplicado</TableHead><TableHead className="text-right">Excedente</TableHead></TableRow></TableHeader><TableBody>{capped.map((r) => <TableRow key={r.id}><TableCell className="font-medium">{r.name}</TableCell><TableCell>{money.format(r.preliminary)}</TableCell><TableCell>{money.format(r.cap)}</TableCell><TableCell className="text-right font-semibold text-amber-400">{money.format(r.remainder)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div> }
