'use client'

import { Download, FileBarChart, FileSpreadsheet, Users } from 'lucide-react'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'

function SectionTitle({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) { return <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[0.18em] text-primary">{eyebrow}</p><h1 className="text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p>}</div>{action}</div> }

export function ReportsView({ onNotify }: { onNotify: (m: string) => void }) { const reports = [{ icon: FileBarChart, title: 'Reporte consolidado', description: 'Resumen del fondo, distribución y remanentes.', meta: '27 trabajadores · Versión 1.2' }, { icon: Users, title: 'Reporte individual', description: 'Detalle de cálculo por cada trabajador.', meta: '27 fichas disponibles' }, { icon: FileSpreadsheet, title: 'Matriz de cálculo', description: 'Factores, topes y fórmulas trazables.', meta: 'Formato Excel' }]; return <div className="flex flex-col gap-7"><SectionTitle eyebrow="Centro de reportes" title="Reportes" description="Genera documentos listos para revisión, firma y archivo." /><div className="grid gap-4 lg:grid-cols-3">{reports.map(({ icon: Icon, title, description, meta }) => <Card key={title}><CardHeader><div className="flex size-10 items-center justify-center rounded-lg bg-primary/8 text-primary"><Icon className="size-5" /></div><CardTitle className="pt-2">{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent><p className="text-xs text-muted-foreground">{meta}</p><div className="mt-4 flex gap-2"><Button size="sm" onClick={() => onNotify(`${title} generado`)}><Download className="mr-2 size-4" />Descargar</Button><Button size="sm" variant="outline" onClick={() => onNotify('Vista de impresión abierta')}>Imprimir</Button></div></CardContent></Card>)}</div><Alert><FileBarChart className="size-4" /><AlertTitle>Documentos auditables</AlertTitle><AlertDescription>Cada reporte conserva la versión del cálculo, usuario responsable y fecha de generación.</AlertDescription></Alert></div> }
