'use client'

import { AlertCircle, Calculator, ClipboardCheck, Filter, MoreHorizontal, Plus, Search, Upload, Users } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { money, number } from '@/lib/utilities-calculation'
import { employees } from '@/lib/utilities-data'

const statusStyle: Record<string, string> = { Calculado: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30', Cerrado: 'bg-slate-500/10 text-slate-300 border-slate-500/30', 'En cálculo': 'bg-amber-500/10 text-amber-400 border-amber-500/30', Borrador: 'bg-blue-500/10 text-blue-400 border-blue-500/30', Completo: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30', Pendiente: 'bg-amber-500/10 text-amber-400 border-amber-500/30', Observado: 'bg-rose-500/10 text-rose-400 border-rose-500/30' }

function Status({ value }: { value: string }) { return <Badge variant="outline" className={`font-medium ${statusStyle[value] || ''}`}>{value}</Badge> }
function SectionTitle({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) { return <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[0.18em] text-primary">{eyebrow}</p><h1 className="text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p>}</div>{action}</div> }
function Kpi({ label, value, hint, tone = 'default', icon: Icon }: { label: string; value: string; hint: string; tone?: 'default' | 'teal' | 'amber' | 'rose'; icon: typeof Calculator }) { return <Card className="border-border/70 shadow-sm"><CardContent className="flex items-start justify-between p-5"><div><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-2 text-xl font-semibold tracking-tight">{value}</p><p className={`mt-1 text-xs ${tone === 'rose' ? 'text-rose-400' : tone === 'amber' ? 'text-amber-400' : tone === 'teal' ? 'text-teal-400' : 'text-muted-foreground'}`}>{hint}</p></div><div className={`rounded-lg p-2.5 ${tone === 'teal' ? 'bg-teal-500/10 text-teal-400' : tone === 'amber' ? 'bg-amber-500/10 text-amber-400' : tone === 'rose' ? 'bg-rose-500/10 text-rose-400' : 'bg-primary/8 text-primary'}`}><Icon className="size-4" /></div></CardContent></Card> }

export function WorkersView({ query, setQuery, employees: list, onNotify }: { query: string; setQuery: (v: string) => void; employees: typeof employees; onNotify: (m: string) => void }) { return <div className="flex flex-col gap-7"><SectionTitle eyebrow="Base de trabajadores" title="Trabajadores" description="Revisa la información computable antes de ejecutar la distribución." action={<div className="flex gap-2"><Button variant="outline" onClick={() => onNotify('Importación de archivo iniciada')}><Upload className="mr-2 size-4" />Importar</Button><Button onClick={() => onNotify('Formulario de trabajador abierto')}><Plus className="mr-2 size-4" />Agregar</Button></div>} /><div className="grid gap-4 sm:grid-cols-3"><Kpi label="Registros" value={number.format(list.length)} hint="Base cargada" icon={Users} tone="teal" /><Kpi label="Completos" value={number.format(list.filter((employee) => employee.status === 'Completo').length)} hint="Sin observaciones" icon={ClipboardCheck} /><Kpi label="Observados" value={number.format(list.filter((employee) => employee.status !== 'Completo').length)} hint="Requieren revisión" icon={AlertCircle} tone="amber" /></div><Card><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle>Lista computable</CardTitle><CardDescription>Última carga: nómina-marzo-2026.xlsx</CardDescription></div><div className="flex gap-2"><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar trabajador" className="w-full pl-9 sm:w-64" /></div><Button variant="outline" size="icon"><Filter className="size-4" /></Button></div></div></CardHeader><CardContent><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Trabajador</TableHead><TableHead>Área</TableHead><TableHead>Días laborados</TableHead><TableHead>Remuneración</TableHead><TableHead>Estado</TableHead><TableHead className="text-right">Acciones</TableHead></TableRow></TableHeader><TableBody>{list.map((employee) => <TableRow key={employee.id}><TableCell><p className="font-medium">{employee.name}</p><p className="text-xs text-muted-foreground">{employee.code} · {employee.role}</p></TableCell><TableCell>{employee.department}</TableCell><TableCell>{number.format(employee.days)}</TableCell><TableCell>{money.format(employee.remuneration)}</TableCell><TableCell><Status value={employee.status} /></TableCell><TableCell className="text-right"><Button variant="ghost" size="icon" onClick={() => onNotify(`Editando a ${employee.name}`)}><MoreHorizontal className="size-4" /></Button></TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card></div> }
